#!/usr/bin/env bash
# Installing nginx on ubuntu

sudo apt update &&
sudo apt -y install nginx
# Firewall port 80
sudo ufw allow 'Nginx HTTP'
# Index file and start
echo "Hello World!" > /var/www/html/index.html &&
sudo /etc/init.d/nginx start
