#!/usr/bin/env bash
# Bash script that: Creates the file /var/run/myscript.pid containing its PID Displays To infinity and beyond indefinitely Displays I hate the kill command when receiving a SIGTERM signal Displays Y U no love me?! when receiving a SIGINT signal Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
sudo touch /var/run/myscript.pid
sudo bash -c "echo $$ > /var/run/myscript.pid"
function sigterm {
    echo "I hate the kill command"
    sudo rm /var/run/myscript.pid
}
function sigquit {
    sudo rm /var/run/myscript.pid
}
function sigint {
    echo "Y U no love me?!"
}
trap sigint SIGINT
trap sigquit SIGQUIT
trap sigterm SIGTERM
i=1
while [ $i -lt 2 ]
do
	echo "To infinity and beyond"
done
