#!/usr/bin/env bash
#Bash script that displays: The content of the current directory In a list format Where only the part of the name after the first dash is displayed
for a in *
do
	echo "$a" | cut -d'' -f2
done
