#!/usr/bin/env bash
#Bash script that gives you information about the school file.
FILE = "school"
if [ -e ./$FILE ];
then
    echo "$FILE file exists"
	if [ ! -s ./$FILE ];
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	if [ ! -d ./$FILE ];
	then
		echo "$FILE is a regular file"
	fi
else
    echo "$FILE file does not exist"
fi
